[package]
name = "crowbar"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
cairo-rs = "0.1"
clap = "2"
pango = "0.1"
xcb = "0.7"
xcb-util = { version = "0.1", features = ["icccm", "ewmh", "thread"] }
